---
  - hosts: webserver
    become_method: sudo
    remote_user: root
    tasks:      
      - name: install nginx
        apt: name=nginx state=latest
      - name: Restart service nginx
        service:
          name: nginx
          state: started
      - name: copy the nginx config file and restart nginx
        copy:
          src: /home/ec2-user/devops-challenge/ansible/static_site.cfg
          dest: /etc/nginx/sites-available/static_site.cfg
        become: yes
      - name: create symlink
        file:
          src: /etc/nginx/sites-available/static_site.cfg
          dest: /etc/nginx/sites-enabled/default
          state: link
        become: yes
      - name: copy the content of the web site
        copy:
          src: /home/ec2-user/devops-challenge/ansible/static-site-src/
          dest: /home/ubuntu/static-site
      - name: restart nginx
        service:
          name: nginx
          state: restarted
        become: yes
        
